package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ሌሎች መጻሕፍት — the church books outside the 81, scanned from printed copies.
 *
 * Ninety-one books and three million characters, so the shelf ([BookIndex]) and
 * the books are separate files: opening the shelf reads a 40 KB index, and
 * opening a book reads only that book. Generated by tools/build_books.py from
 * the scans in the repo root; never edited by hand.
 */
@Serializable
data class BookBlock(
    val type: String = "paragraph",
    val text: String = "",
    /** 1 for a chapter head, 2 for a section head inside it. */
    val level: Int = 0,
    /** "gez" or "amh" — a bilingual book sets its Amharic apart from its Ge'ez. */
    val lang: String = "gez",
    /**
     * Character ranges the printed page sets in red, as `[[start, end], …]`.
     *
     * Carried in the data rather than derived, because a ዜማ book's red is an
     * editorial decision per line: the printer reddens the incipit, the
     * performance direction and a name when it carries the stanza, then leaves
     * the same name black two lines later. A መልክእ's red is a rule and stays a
     * rule — see Rubrication.
     */
    val red: List<List<Int>> = emptyList(),
    val speaker: String? = null,
    val rubric: String? = null,
    val targetAnatomy: String? = null,
) {
    val isHeading: Boolean get() = type == "heading"
    val isAmharic: Boolean get() = lang == "amh"

    /** [red] as ranges, dropping anything the text cannot honour. */
    val redRanges: List<IntRange>
        get() = red.mapNotNull { pair ->
            val from = pair.getOrNull(0) ?: return@mapNotNull null
            val to = pair.getOrNull(1) ?: return@mapNotNull null
            if (from in 0..text.length && to in from..text.length) from until to else null
        }
}

@Serializable
data class BookChapter(
    val number: Int = 0,
    val title: String = "",
    val blocks: List<BookBlock> = emptyList(),
    /** Which scanned copy this chapter came from, when a book merges several. */
    val source: String? = null,
)

@Serializable
data class Book(
    val id: String = "",
    val title: String = "",
    val shelf: String = "",
    val chapters: List<BookChapter> = emptyList(),
)

/** One book's row on the shelf — everything the list needs without opening it. */
@Serializable
data class BookMeta(
    val id: String = "",
    val title: String = "",
    val shelf: String = "",
    val chapterCount: Int = 0,
    val blockCount: Int = 0,
    val charCount: Int = 0,
    /** "gez", "amh", or "mixed" when the Amharic runs beside the Ge'ez. */
    val lang: String = "gez",
    val titledChapters: Int = 0,
    /** Homophone-folded title: what a ማኅሌት part name matches to open this book. */
    val key: String = "",
    /**
     * Other folded names this book answers to.
     *
     * A ማኅሌት movement is not always named after the book it comes out of: the
     * ነግሥ parts are chanted from ዜማ ዘነግሥ without ever saying so. Where the
     * corpus shows the connection, the alias records it.
     */
    val altKeys: List<String> = emptyList(),
    val sources: List<String>? = null,
    /** Second recensions of this same hymn, named "… ካልዕ" in the books. */
    val variants: List<BookRef> = emptyList(),
    /** Set on a ካልዕ, pointing back at the recension it is a second copy of. */
    val variantOf: BookRef? = null,
    val comingSoon: Boolean = false,
)

/** A pointer from one book to another, enough to label and open it. */
@Serializable
data class BookRef(val id: String = "", val title: String = "")

@Serializable
data class BookShelf(
    val key: String = "",
    val name: String = "",
    val subtitle: String = "",
    val books: List<BookMeta> = emptyList(),
)

@Serializable
data class BookIndex(
    val contentVersion: Int = 1,
    val shelves: List<BookShelf> = emptyList(),
)
