package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ሌሎች መጻሕፍት — the church books outside the 81, scanned from printed copies.
 *
 * Ninety-one books and three million characters, so the shelf ([BookIndex]) and
 * the books are separate files: opening the shelf reads a 40 KB index, and
 * opening a book reads only that book. Generated by tools/build_books.py from
 * the scans in the repo root; never edited by hand.
 */
@Serializable
data class BookBlock(
    val type: String = "paragraph",
    val text: String = "",
    /** 1 for a chapter head, 2 for a section head inside it. */
    val level: Int = 0,
    /** "gez" or "amh" — a bilingual book sets its Amharic apart from its Ge'ez. */
    val lang: String = "gez",
) {
    val isHeading: Boolean get() = type == "heading"
    val isAmharic: Boolean get() = lang == "amh"
}

@Serializable
data class BookChapter(
    val number: Int = 0,
    val title: String = "",
    val blocks: List<BookBlock> = emptyList(),
    /** Which scanned copy this chapter came from, when a book merges several. */
    val source: String? = null,
)

@Serializable
data class Book(
    val id: String = "",
    val title: String = "",
    val shelf: String = "",
    val chapters: List<BookChapter> = emptyList(),
)

/** One book's row on the shelf — everything the list needs without opening it. */
@Serializable
data class BookMeta(
    val id: String = "",
    val title: String = "",
    val shelf: String = "",
    val chapterCount: Int = 0,
    val blockCount: Int = 0,
    val charCount: Int = 0,
    /** "gez", "amh", or "mixed" when the Amharic runs beside the Ge'ez. */
    val lang: String = "gez",
    val titledChapters: Int = 0,
    /** Homophone-folded title: what a ማኅሌት part name matches to open this book. */
    val key: String = "",
    val sources: List<String>? = null,
    /** Second recensions of this same hymn, named "… ካልዕ" in the books. */
    val variants: List<BookRef> = emptyList(),
    /** Set on a ካልዕ, pointing back at the recension it is a second copy of. */
    val variantOf: BookRef? = null,
)

/** A pointer from one book to another, enough to label and open it. */
@Serializable
data class BookRef(val id: String = "", val title: String = "")

@Serializable
data class BookShelf(
    val key: String = "",
    val name: String = "",
    val subtitle: String = "",
    val books: List<BookMeta> = emptyList(),
)

@Serializable
data class BookIndex(
    val contentVersion: Int = 1,
    val shelves: List<BookShelf> = emptyList(),
)
