package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * One day of the ወርኀዊ በዓላት cycle — the saints commemorated on a given day of
 * EVERY Ethiopian month. Generated by tools/extract_holidays.py from the
 * bundled ስንክሳር's own "📌 ወርኀዊ በዓላት" blocks, so the names are the church's,
 * not the app's.
 *
 * [primary] is the name the sources list first; [also] is everything else the
 * months agree on, which matters because the famous name for a day is not
 * always the first one printed (ቀን ፳፫ leads with ልበ አምላክ ቅዱስ ዳዊት, while most
 * people know it as ቅዱስ ጊዮርጊስ).
 */
@Serializable
data class MonthlyHoliday(
    val day: Int,
    val primary: String,
    val also: List<String> = emptyList(),
    /** How many of the twelve months carried this day's block — provenance. */
    val months: Int = 0,
) {
    /** "ቅዱስ ሚካኤል ሊቀ መላእክት · ቅዱስ ማቴዎስ ሐዋርያ" — the day at a glance. */
    val summary: String
        get() = (listOf(primary) + also.take(2)).joinToString(" · ")
}

/**
 * A yearly feast a vow can be anchored to. Fixed feasts sit on an Ethiopian
 * month and day; movable ones are computed per year from the ባሕረ ሓሳብ, so they
 * carry a [movableKey] instead of a date.
 */
@Serializable
data class AnnualHoliday(
    val key: String,
    val nameAm: String,
    val nameEn: String,
    val monthNum: Int? = null,
    val day: Int? = null,
    val movableKey: String? = null,
) {
    val movable: Boolean get() = movableKey != null
}
