package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ሥርዓተ ማኅሌት — the orders of service, merged from the scanned chant book, the
 * ዘመነ ጽጌ አቋቋም, and the ግጻዌ.
 *
 * The scanned book is the spine: 95 orders across all thirteen months, each
 * headed with its date, where the ግጻዌ's ማኅሌት stopped after ሚያዝያ. Six ግጻዌ orders
 * the scan does not carry are folded in and keep their source. And ዘመነ ጽጌ,
 * which the ግጻዌ could only give as an ordinal week because the season floats,
 * arrives dated: one order per date its Sundays can land on.
 *
 * Bundled under assets/content/mahlet/, generated by tools/build_mahlet.py.
 */
@Serializable
data class MahletPart(
    /** Its liturgical role — ዚቅ, ወረብ, ነግሥ, መልክአ ሥላሴ. Empty where the scan gave none. */
    val key: String = "",
    val verse: String = "",
)

@Serializable
data class MahletOrder(
    val id: String = "",
    /** [MahletKind.VIGIL] the evening before, [MahletKind.MAHLET] at dawn. */
    val kind: String = MahletKind.MAHLET,
    /** The feast, as the book names it. */
    val feast: String = "",
    /** Ethiopian month 1–13, or null for an order the books do not date. */
    val month: Int? = null,
    val day: Int? = null,
    /** "tsige" for ዘመነ ጽጌ; null otherwise. */
    val season: String? = null,
    /**
     * True for a ጽጌ order appointed by [day] falling on a Sunday, rather than
     * by the day itself — which is how the አቋቋም books are set, and why the
     * season needed the calendar rather than an ordinal week.
     */
    val whenSunday: Boolean = false,
    /** Which book it came from, when that is not the scanned spine. */
    val source: String? = null,
    val parts: List<MahletPart> = emptyList(),
)

object MahletKind {
    const val VIGIL = "vigil"
    const val MAHLET = "mahlet"
}

object MahletSeason {
    const val TSIGE = "tsige"
}

/** One order's row in the index — everything a list needs without opening it. */
@Serializable
data class MahletOrderMeta(
    val id: String = "",
    val kind: String = MahletKind.MAHLET,
    val feast: String = "",
    val day: Int? = null,
    val season: String? = null,
    val whenSunday: Boolean = false,
    val source: String? = null,
    val parts: Int = 0,
)

@Serializable
data class MahletMonth(
    /** 0 for the orders no book dates. */
    val month: Int = 0,
    val name: String = "",
    val orders: List<MahletOrderMeta> = emptyList(),
)

@Serializable
data class MahletIndex(
    val contentVersion: Int = 1,
    val months: List<MahletMonth> = emptyList(),
)
