package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ሥርዓተ ማኅሌት — the orders of service, merged from the editorial edition of
 * the scanned chant book and the Telegram editions, the ዘመነ ጽጌ አቋቋም, and the
 * ግጻዌ.
 *
 * The merged edition is the spine: the book's own orders across the year, and
 * beside each the Telegram editions of it as [MahletOrder.versions] — editions
 * to choose between, never a continuation of the book's text. Where the book
 * has no order and an edition does, that edition stands for it and says so in
 * [MahletOrder.source]. A part marked [MahletPart.alternative] is "ወይም": the
 * book or an edition offers it in place of the part before, not after it.
 * ዘመነ ጽጌ arrives dated, one order per date its Sundays can land on; the ግጻዌ
 * contributes only the orders nothing else carries.
 *
 * Bundled under assets/content/mahlet/, generated by tools/build_mahlet.py.
 */
@Serializable
data class MahletPart(
    /** Its liturgical role — ዚቅ, ወረብ, ነግሥ, መልክአ ሥላሴ. Empty where the scan gave none. */
    val key: String = "",
    val verse: String = "",
    /**
     * Offered in place of the part before it, not sung after it. The book marks
     * these and the Telegram editions nest them; both mean "or", and the page
     * must say so or a choice reads as a sequence.
     */
    val alternative: Boolean = false,
)

/**
 * One Telegram edition of an order — a whole alternative text, to be read in
 * place of the book's, never appended to it. [url] is the post it came from.
 */
@Serializable
data class MahletVersion(
    val id: String = "",
    val title: String? = null,
    val url: String? = null,
    val parts: List<MahletPart> = emptyList(),
)

@Serializable
data class MahletOrder(
    val id: String = "",
    /** [MahletKind.VIGIL] the evening before, [MahletKind.MAHLET] at dawn. */
    val kind: String = MahletKind.MAHLET,
    /** The feast, as the book names it. */
    val feast: String = "",
    /** Ethiopian month 1–13, or null for an order the books do not date. */
    val month: Int? = null,
    val day: Int? = null,
    /** "tsige" for ዘመነ ጽጌ; null otherwise. */
    val season: String? = null,
    /**
     * True for a ጽጌ order appointed by [day] falling on a Sunday, rather than
     * by the day itself — which is how the አቋቋም books are set, and why the
     * season needed the calendar rather than an ordinal week.
     */
    val whenSunday: Boolean = false,
    /** Which book it came from, when that is not the scanned spine. */
    val source: String? = null,
    /**
     * For a feast the book cannot date because it moves with Fasika or sits on
     * a Sunday the calendar has to find: the key [com.agpeya.app.data.MahletComputus]
     * appoints it by. Null for a feast with a day of its own.
     */
    val movable: String? = null,
    val parts: List<MahletPart> = emptyList(),
    /** The editions of this order, to choose between. Empty for most. */
    val versions: List<MahletVersion> = emptyList(),
)

object MahletKind {
    const val VIGIL = "vigil"
    const val MAHLET = "mahlet"
    const val ANGERGARI = "angergari"
    const val PROCESSION = "procession"
    const val PRAYER = "prayer"
    const val UNSPECIFIED = "unspecified"

    /** The night's ዋዜማ before the morning's ማኅሌት, and the rarer kinds after. */
    fun rank(kind: String): Int = when (kind) {
        VIGIL -> 0
        MAHLET -> 1
        ANGERGARI -> 2
        PROCESSION -> 3
        PRAYER -> 4
        else -> 5
    }
}

object MahletSeason {
    const val TSIGE = "tsige"
}

/**
 * The values [MahletOrder.source] takes, as the builder writes them. Amharic
 * because the list shows them beside an order; constants because code that
 * filters on them should not be matching a loose string.
 */
object MahletSource {
    /** An order standing on a Telegram edition, the book having none. */
    const val TELEGRAM = "ቴሌግራም"
    const val GITSAWE = "ግጻዌ"
    const val TSIGE_AKWAKWAM = "ማኅሌተ ጽጌ አቋቋም"
}

/** One order's row in the index — everything a list needs without opening it. */
@Serializable
data class MahletOrderMeta(
    val id: String = "",
    val kind: String = MahletKind.MAHLET,
    val feast: String = "",
    val day: Int? = null,
    val season: String? = null,
    val whenSunday: Boolean = false,
    val source: String? = null,
    val movable: String? = null,
    val parts: Int = 0,
    /** How many editions the order has besides the one shown. */
    val versions: Int = 0,
)

@Serializable
data class MahletMonth(
    /** 0 for the orders no book dates. */
    val month: Int = 0,
    val name: String = "",
    val orders: List<MahletOrderMeta> = emptyList(),
)

@Serializable
data class MahletIndex(
    val contentVersion: Int = 1,
    val months: List<MahletMonth> = emptyList(),
)
