package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * Content models, deserialized from the bundled JSON files under
 * assets/content (generated by tools/extract_content.py — never edited
 * by hand). IDs are permanent contracts: bookmarks and reminders
 * reference them across app updates.
 */
@Serializable
data class Hour(
    val id: String,
    val orderIndex: Int,
    val name: String,
    val transliteration: String,
    val timeHint: String,
    val sections: List<Section>,
)

@Serializable
data class Section(
    val id: String,
    val orderIndex: Int,
    val type: String,
    val title: String,
    val subtitle: String? = null,
    val reference: String? = null,
    /** Watch label for the Midnight hour (e.g. "ክፍል ፩"); null elsewhere. */
    val part: String? = null,
    /** Bible verse number of verses[0] — gospel passages start mid-chapter. */
    val firstVerse: Int = 1,
    val verses: List<String>,
)

/**
 * A user's personal customization of one hour: the order of section ids and
 * which sections are hidden. Empty = default order, nothing hidden. The prayer
 * text is never changed — only what shows and in what order.
 */
@Serializable
data class HourLayout(
    val order: List<String> = emptyList(),
    val hidden: Set<String> = emptySet(),
)

/** A saved bookmark — a snapshot so the bookmarks list renders without rescanning content. */
@Serializable
data class Bookmark(
    val hourId: String,
    val hourName: String,
    val sectionId: String,
    val sectionIndex: Int,
    val title: String,
    val subtitle: String? = null,
)

@Serializable
data class Manifest(
    val contentVersion: Int,
    val hours: List<ManifestHour>,
)

@Serializable
data class ManifestHour(
    val id: String,
    val file: String,
)
