package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * The bundled New Testament (assets/content/scripture/), generated by
 * tools/extract_scripture.py from the same 80-weahadu 1962 Amharic export the
 * Psalter was built from — so its orthography matches the rest of the app.
 *
 * It exists to back the ግጻዌ (Gitsawe) reading links: a Gospel/Epistle reference
 * in the lectionary resolves to a passage here. Never hand-edited.
 */

/** Lightweight manifest entry — enough to list/route without loading a book. */
@Serializable
data class ScriptureBookMeta(
    val number: Int,
    val key: String,
    val nameAm: String,
    val nameEn: String,
    val chapters: Int,
)

@Serializable
data class ScriptureManifest(
    val contentVersion: Int,
    val books: List<ScriptureBookMeta>,
)

@Serializable
data class ScriptureBook(
    val number: Int,
    val key: String,
    val nameAm: String,
    val nameEn: String,
    val chapters: List<ScriptureChapter>,
)

@Serializable
data class ScriptureChapter(
    val chapter: Int,
    val verses: List<ScriptureVerse>,
)

/** One verse: its number [n] (versification can have gaps) and [text]. */
@Serializable
data class ScriptureVerse(
    val n: Int,
    val text: String,
)
