package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ስንክሳር (Synaxarium) — the daily commemorations of the Ethiopian Orthodox
 * church year, in two editions: አማርኛ and ግእዝ.
 *
 * The scans carry the book's own structure, so nothing here is inferred from
 * prose. A day is its heading, its commemorations, the saints it names, and the
 * reading it closes on; a commemoration is numbered paragraphs closed by its
 * [SynaxariumEntry.arke]. Bundled under assets/content/sinksar/ as one file per
 * month per edition, generated by tools/build_sinksar.py. Never edited by hand.
 */
@Serializable
data class SynaxariumParagraph(
    /** The paragraph's own Ge'ez number; 0 where the scan left it unnumbered. */
    val n: Int = 0,
    val text: String = "",
)

/** One commemoration: its narrative, and the hymn that closes it. */
@Serializable
data class SynaxariumEntry(
    /**
     * Content-addressed, from the opening of the entry. Bookmarks point at this,
     * so it must not move when the day is re-split — which the old
     * index-within-the-day id did, renaming every entry after any change.
     */
    val id: String = "",
    val paragraphs: List<SynaxariumParagraph> = emptyList(),
    /** The አርኬ, its stanzas separated by newlines. Null where the day has none. */
    val arke: String? = null,
) {
    val text: String get() = paragraphs.joinToString("\n") { it.text }

    /** The first line of the first paragraph — what a bookmark is titled by. */
    val heading: String
        get() = paragraphs.firstOrNull()?.text?.substringBefore('።')?.trim().orEmpty()
}

/**
 * The day's scripture and the reference it came from, as one thing.
 *
 * The scan writes them as two blocks and they were rendered as two, which let
 * the citation be selected, copied and shared on its own as though it were a
 * paragraph of the book.
 */
@Serializable
data class SynaxariumReading(
    val text: String = "",
    val cite: String? = null,
)

@Serializable
data class SynaxariumDay(
    val day: Int = 0,
    /** "ስንክሳር ዘወርኀ ጥቅምት ፫" — the book's own heading for the day. */
    val header: String = "",
    val entries: List<SynaxariumEntry> = emptyList(),
    /** The saints the day commemorates annually. */
    val feasts: List<String> = emptyList(),
    /** ወርኀዊ በዓላት — the ones kept on this day of every month. */
    val monthly: List<String> = emptyList(),
    val reading: SynaxariumReading? = null,
)

@Serializable
data class SynaxariumMonth(
    val month: Int = 0,
    val name: String = "",
    val edition: String = SynaxariumEdition.AMHARIC,
    val contentVersion: Int = 1,
    val days: List<SynaxariumDay> = emptyList(),
)

/** Which of the two editions is being read. */
object SynaxariumEdition {
    const val AMHARIC = "am"
    const val GEEZ = "ge"

    /**
     * The two are parallel editions, not a parallel text: only 30 of 366 days
     * have the same paragraph count in both, so they are read one at a time and
     * never set side by side, which would pair the wrong paragraphs.
     */
    val all = listOf(AMHARIC, GEEZ)
}

@Serializable
data class SynaxariumMonthMeta(
    val month: Int = 0,
    val name: String = "",
    val days: Int = 0,
)

@Serializable
data class SynaxariumEditionMeta(
    val code: String = "",
    val name: String = "",
)

@Serializable
data class SynaxariumManifest(
    val contentVersion: Int = 1,
    val editions: List<SynaxariumEditionMeta> = emptyList(),
    val months: List<SynaxariumMonthMeta> = emptyList(),
)
