package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ስንክሳር (Synaxarium) — the daily commemorations of saints and events of the
 * Ethiopian Orthodox church year. Bundled under assets/content/sinksar/, one
 * file per Ethiopian month, generated by tools/extract_sinksar.py. Never edited
 * by hand.
 */
@Serializable
data class SynaxariumMonth(
    val month: Int,
    val days: List<SynaxariumDay> = emptyList(),
)

@Serializable
data class SynaxariumDay(
    val day: Int,
    val entries: List<SynaxariumEntry> = emptyList(),
)

/** One commemoration: its [title] (saint/event) and the narrative [text]. */
@Serializable
data class SynaxariumEntry(
    val title: String = "",
    val text: String = "",
)

@Serializable
data class SynaxariumMonthMeta(
    val month: Int,
    val name: String,
    val days: Int,
)

@Serializable
data class SynaxariumManifest(
    val contentVersion: Int,
    val months: List<SynaxariumMonthMeta> = emptyList(),
)
