package com.agpeya.app.model

import kotlinx.serialization.Serializable

/**
 * ውዳሴ ማርያም (Wudase Maryam) — the daily Praise of Mary. One [WudaseSection] per
 * weekday (plus a few appended prayers), each carrying the text in both Ge'ez
 * ([ge]) and Amharic ([am]) as numbered stanzas. Bundled under
 * assets/content/wudase/, generated by tools/build_wudase.py. Never edited by hand.
 */
@Serializable
data class WudaseSection(
    val id: String,
    /** 1=Monday … 7=Sunday for the day cycle; 0 for an appended prayer. */
    val weekday: Int = 0,
    /** Short chip label (Amharic). */
    val label: String = "",
    val titleAm: String = "",
    val titleGe: String = "",
    val am: List<String> = emptyList(),
    val ge: List<String> = emptyList(),
)

@Serializable
data class WudaseContent(
    val contentVersion: Int = 1,
    val sections: List<WudaseSection> = emptyList(),
)
